### PR TITLE
feature (website): new page for recipient selection 

### PR DESCRIPTION
**Pull request by ssandino**
## Release Notes

- **New Features**
  - Enhanced FAQ section with a new "selection" topic, detailing the recipient selection process for the Social Income program in multiple languages.
  - New components introduced: `ScrollToChevron`, `HeroSection`, `PastRounds`, `Resources`, and `SelectionProcess` to improve user navigation and information display.
  - Added localized content for the website selection interface in German, French, and Italian.
  - New `DrawCard` component to display information about completed draws.

- **Bug Fixes**
  - Improved styling and responsiveness in various components.

- **Documentation**
  - Updated FAQ content for clarity and transparency regarding selection criteria and processes across different languages.

- **Refactor**
  - Streamlined component imports and structure for better maintainability.

- **Chores**
  - Added `luxon` dependency for improved date handling.

### CODE REVIEW

**Comment by ssandino** [comment]
@CluEleSsUK while redesigning the new selection page ([preview](https://public-git-sandino-new-recipient-selection-page-social-income.vercel.app/en/ch/transparency/random-selection)) I saw that the link to the drand page seems broken. 

However, this is also the case of the [current page on production](https://socialincome.org/en/int/transparency/recipient-selection). If you click "Confirm on drand" you get forwarded to a page that says: 

> Requested future beacon

Did something change in API of drand? If it's still possible to link it, then it would also be fine to do it for this draft PR (as it will replace the production page soon)

**Comment by CluEleSsUK** [comment]
Ahh, the URL is pointing to our `default` network when the newer (all of?) draws were actually from `quicknet`.
For the latest draw, the URL should be `https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/public/11521685`.  You can stick that big ugly weird bit in the middle of the URLs to show the right thing, and perhaps I can update the template or tool

**Comment by ssandino** [comment]
@mkue  I’ve moved it from draft to review, as we’re nearly there. The only key item left is displaying the total donation amount collected (same as on the […/finances page](https://socialincome.org/en/int/transparency/finances/chf)). This I would need your help. 

Including the sticky elements on the right would be a nice touch, but we can prioritize an early release and address that in a follow-up PR. There’s also potential to enhance navigation, like adding a scroll-to-next-section feature when clicking the arrow, or other interactive elements. However, these extras could delay the new page’s launch (main goal).

Check it out in the [Vercel preview link](https://public-git-sandino-new-recipient-selection-page-social-income.vercel.app/en/ch/transparency/random-selection).

**Comment by ssandino** [comment]
> Ahh, the URL is pointing to our default network when the newer (all of?) draws were actually from quicknet.
For the latest draw, the URL should be https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/public/11521685. You can stick that big ugly weird bit in the middle of the URLs to show the right thing, and perhaps I can update the template or tool

@CluEleSsUK I’ve now resolved this with the proposed URL adjustment. This is an improvement, as the most recent rounds now display the correct random number and future drafts will also be accurate. We’re only off for the first draft (`20/10/2023`), since we probably used the `default` network at this time.

**Comment by ssandino** [comment]
@mkue added all translations, so it’s ready to publish from my side. 

There are two optimizations that would be nice but can be included in a future deployment:
1.	Display the total donations dynamically with currency and amount. (It’s currently set to 300,000+, with the plus sign newly added, so it’s fine to deploy as it accurately shows a rounded minimum instead of an exact figure). Also depends on #927 
2.	Box: Update the sticky element to activate as soon as the second section (Transparent Selection) comes into view (passes the box). And align `title` and `subtitle` left
Screenshot 2024-11-08 at 17 09 05

**Review by mkue — APPROVED** [review]

**Pull request merged**
