### PR TITLE
feature(website): animated logo

### PR DESCRIPTION
**Pull request by MoarCoding**
This replaces the top navbar's logo with a Lottie animation

Note: Not ready to be merged until lottie-file's whitespace has been pruned and the text only animates to the right.

### CODE REVIEW

**Comment by ssandino** [comment]
@MoarCoding [here](https://public-git-fork-moarcoding-issue-743-imple-b2cfb8-social-income.vercel.app/en/ch) you can see the preview deployment. I see that the Lottie file itself is centred in its div and could be left aligned.

Screenshot 2024-02-09 at 14 46 12

**Comment by MoarCoding** [comment]
@ssandino Exactly. I tried editing the lottie myself, but in the end I failed to find one that let me save the result as json. Figured it would be easier for you guys to just update it according to your wishes.

**Comment by ssandino** [comment]
@MoarCoding we have now an updated version of the Lottie file thanks to @RaphaelSchoen1. See [comment in issue](https://github.com/socialincome-san/public/issues/743#issuecomment-1936994832). Would you be able to update before the review?

**Comment by MoarCoding** [comment]
@ssandino I'm on it. Sorry for the delay, I only code during office hours.

**Comment by ssandino** [comment]
Thanks @MoarCoding – the preview deployment has currently an error, but seems unrelated to the animated logo.

**Comment by mkue** [comment]
Thanks for you work @MoarCoding 

I disabled the looping of the animation now by default. It looks weird if the animation keeps repeating.

The downside of the animated logo is that it doesn't work with statically created pages (it requires JS). This means, that the logo is blank when the page loads and then there's some flickering.

I think we should prevent this. Do you want to look into this @MoarCoding? Let me know if you need more info.

**Comment by ssandino** [comment]
Discussed with @RaphaelSchoen1 if the loop can be disabled directly in the Lottie file (and therefore replace the current file), but it turns out this has to be done directly in the code: 
[see API documentation](https://github.com/lottie-react-native/lottie-react-native/blob/master/docs/api.md) -> Loop

A fallback option would be great!

**Comment by MoarCoding** [comment]
> Thanks for you work @MoarCoding
> 
> I disabled the looping of the animation now by default. It looks weird if the animation keeps repeating.
> 
> The downside of the animated logo is that it doesn't work with statically created pages (it requires JS). This means, that the logo is blank when the page loads and then there's some flickering.
> 
> I think we should prevent this. Do you want to look into this @MoarCoding? Let me know if you need more info.

Absolutely. I'm away on vacation right now, but I'll be happy to look into this come monday.

**Comment by MoarCoding** [comment]
@ssandino I've pushed a fallback. Still looks a bit weird IMO since the lottie's starting frame doesn't look like the fallback, but I figured that it's up to you to figure out what you're after here

**Comment by ssandino** [comment]
> @ssandino I've pushed a fallback. Still looks a bit weird IMO since the lottie's starting frame doesn't look like the fallback, but I figured that it's up to you to figure out what you're after here

Thanks @MoarCoding I will try to replace the current fallback logo with the first frame (exported as SVG) of the animation. Theoretically it should then be seamless. Let me try that. 

While testing I found a weird bug on Safari. The logo itself is not left aligned. Any solution to this? 

Screenshot 2024-03-01 at 15 10 12

**Comment by MoarCoding** [comment]
> > @ssandino I've pushed a fallback. Still looks a bit weird IMO since the lottie's starting frame doesn't look like the fallback, but I figured that it's up to you to figure out what you're after here
> 
> Thanks @MoarCoding I will try to replace the current fallback logo with the first frame (exported as SVG) of the animation. Theoretically it should then be seamless. Let me try that.
> 
> While testing I found a weird bug on Safari. The logo itself is not left aligned. Any solution to this?
> 
> Screenshot 2024-03-01 at 15 10 12

Can't confirm since I don't have access to safari. Does it work without my changes?

**Comment by ssandino** [comment]
thanks for the hint. let me see if I find the bug. I get back to you.

**Comment by ssandino** [comment]
> thanks for the hint. let me see if I find the bug. I get back to you.

The wrapping didn't work. @renestalder do you have a good idea?

**Comment by renestalder** [comment]
@MoarCoding @ssandino 

1. Set the parent `<a>` to be an `inline-block`. You can't have an inline element containing block elements.
2. Remove `height:38px` from the parent `div` and set the target width on the `<svg>`. It's set to `width: 100%`. Of course it takes the whole width. ou can use `aspect-ratio` CSS property to then enforce constraints.

And then you get this:

Screenshot 2024-03-04 at 10 46 57

**Comment by renestalder** [comment]
@MoarCoding @ssandino Regarding Lottie files: These files are relatively huge compared to what they do. We should make sure that stuff is loaded non-render blocking to not slow down the website with unnecessary animations on slow connections, using async `import()` or a `React.Lazy` on a higher level.

**Comment by ssandino** [comment]
Thanks @renestalder (added you as reviewer). @MoarCoding would these pointers help to update the PR and wrap up the issue? As we start a large campaign later in the week, it would be amazing to get your branch deployed by Friday. Possible?

**Comment by MoarCoding** [comment]
@ssandino Hi. Unfortunately I'll be extremely busy at work this week since I've just started a new assignment. Would it be possible for @renestalder to fix this himself?

**Pull request closed without merging**
