### PR TITLE
Website: Animated logo

### LINKED ISSUE #743: [Website Feature]: Implement animated logo
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We currently use a static text logo on the top left of the website instead of the animated text logo. 

[Social Income Logo Animation.json (Lottie Export)](https://github.com/socialincome-san/public/files/14201388/Soical.Income.Logo.Animation.json)

You can preview the animation by uploading the json file (above) to [this site](https://drawer.design/preview-lottie-animation/).

### Describe the solution/feature

Adding the animated logo – this requires to use [Lottie React Player](https://github.com/LottieFiles/lottie-react). A good start is these articles: [The easiest way to handle animations In React/Nextjs](https://medium.com/@seun.thedeveloper/the-easiest-way-to-handle-animations-in-react-nextjs-5934a689a010) and [How To Use Lottie Animations in a React App](https://lottiefiles.com/blog/working-with-lottie-animations/how-to-use-lottie-in-react-app/)

The mobile view with the icon logo should not be changed. 

### Describe alternatives you've considered

_No response_

### Criteria for Completion

_No response_

### Anything else?

_No response_

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

### PR DESCRIPTION
**Pull request by dnhn**
Resolve #743

Implemented the animated logo. The player is configured to run once at the beginning but includes a loop option if you prefer.

## Summary by CodeRabbit

- **New Features**
	- Introduced an animated logo component (`SIAnimatedLogo`) that enhances the visual appeal of the website's navigation.
	- Added a new animation file for the logo, providing a dynamic visual experience.

- **Bug Fixes**
	- Replaced the static logo with the animated version in both mobile and desktop navigation components, ensuring a consistent branding experience.

- **Chores**
	- Added a new dependency for the animated logo functionality (`@lottiefiles/react-lottie-player`).

### CODE REVIEW

**Comment by ssandino** [comment]
Looking good @dnhn! Testing on different screens: 

- [x]  Large: animation of logo works well ✅ 
- [x]  Medium: not applicable (as we show only icon) ✅
- [ ]  Small: animation is not playing (see video from iPhone 14 test)

D1F189FA-E3B5-4135-A90A-D9CADCD06B3F_1_102_o

**Comment by dnhn** [comment]
Added to mobile!

> Looking good @dnhn! Testing on different screens:

**Comment by ssandino** [comment]
Looks now good on mobile too

**Review by mkue — APPROVED** [review]
Nice! This works great 🙌🏼 Thank you for your contribution :)

**Pull request merged**
