### PR TITLE
refactor(recipients_app): Align files names with flutter conventions 

### PR DESCRIPTION
**Pull request by MDikkii**

### CODE REVIEW

**Comment by renestalder** [comment]
@MDikkii I don't think I can review that, as I have no knowledge with Flutter and dart.

**Comment by MDikkii** [comment]
It seems that you are selected by default as code owner / admin.

**Comment by ssandino** [comment]
@MDikkii @renestalder solving it (had to do with email forwarding from dev@ email who was code owner, thx Rene for finding out)

**Review by novas1r1 — APPROVED** [review]

**Comment by novas1r1** [comment]
Looks good :)!

**Review by ssandino — APPROVED** [review]

**Pull request merged**
