### PR TITLE
Added datalist element.

### PR DESCRIPTION
**Pull request by soumdatta81**
###  About the PR:
I have added a datalist element to the HTML using React and filled it with data from a Cloud Firestore database. However, I am not sure if the data will be retrieved because I haven’t passed the Firebase configuration object but also at the same time I don't think that will matter. In short, I am a little confused so I am doing a PR for you folks to check this and let me know if there are any issues.

refs https://github.com/socialincome-san/public/issues/181

### CODE REVIEW

**Comment by soumdatta81** [comment]
Kindly look into this @renestalder @mkue

**Review by andrashee — COMMENTED** [review]
We are using Next.js for the website. 

In next.js under `/website/pages` you put the individual website pages. Website specific `components` are in the `website/components` directory.

The plan is however to extract generic, reusable UI components into the `/ui/` package. See the readme and  the existing components in there.

Since with next.js we can render pages statically at build time or on the server (instead on the client) we can use the admin firestore sdk. [Here](https://github.com/socialincome-san/public/blob/main/website/pages/transparency/finances/%5Bcurrency%5D.tsx) a dummy example how to leverage next.js `getStaticProps` to query firestore.

I would start with creating a generic datalist component (which takes the arguments as parameters without any firestore dependency) in the `ui` package and then use that one in the `website` module.

**Comment by renestalder** [comment]
> I would start with creating a generic datalist component (which takes the arguments as parameters without any firestore dependency) in the `ui` package and then use that one in the `website` module.

This approach, is mainly coming from Sandino and me. I recommended creating a first version of the component with a datalist just in place where it is actually used. And then we replace it later with a component from the UI library as soon I have an advanced one ready. Just to not lose time with the tooling and get a first usable prototype up and running.

**Comment by renestalder** [comment]
(updated the first comment in the merge request with the related ticket, for clarity)

**Comment by soumdatta81** [comment]
Added a new PR #258

**Comment by ssandino** [comment]
I close this PR as it got an update in #258

**Pull request closed without merging**
