### PR TITLE
(website) refactor: footer migration

### PR DESCRIPTION
**Pull request by anthonyray**
- This PR introduces two new components : `Footer` (server-side component), `FooterClient` (client-side component). These components are added to the default layout of the website to create the footer section.
- This PR refactors some _language switching_ logic happening in the navbar component to **share it with the footer components**. 

I still need some help before moving from draft to final P.R : 
- [ ] Code Formatting + Linting
- [ ] Footer items translations
While items of the footer are translated for the old website, I don't see those translations available in the assets. 
- [ ] Combobox display bug for small viewports
- [x] Icons validation
I'm using icons from `heroicons`, and they don't match the previous icons (cf screenshot)

### CODE REVIEW

**Comment by ssandino** [comment]
**Icons validation:** This works. Using the `heroicons` is the intended approach and we choose similar icons to the current set of icons. We might change at a later, after discussing it with Raphael and Johannes.

**Comment by ssandino** [comment]
**Footer items translations:** you could add directly in the `website-common.json` file of the respective language path (analog to how we handle the translations for the navigation)

**Comment by mkue** [comment]
> [ ] Code Formatting + Linting

You can just run `npm run format-code`. This will make all formatting changes.

I hope everything else is clear. Otherwise, just ping me.

**Comment by mkue** [comment]
I invited you to the team on GitHub now so that you have access to this repository. If you like, you can make the PR from a branch within this repository, then all the GitHub actions should run through as well.

**Comment by anthonyray** [comment]
Thanks people for all your remarks, I'm moving this P.R over to #568 now that I'm a member of the team. 
I will close this P.R here, and continue the discussion in #568 . See you there !

**Pull request closed without merging**
