### PR TITLE
feature(website): merge existing webpages into /legal page

### PR DESCRIPTION
**Pull request by DarkMenacer**

### CODE REVIEW

**Comment by ssandino** [comment]
Nice job @DarkMenacer – I made a commit with amendments to the DE translations, as well minor changes to the EN. I see some translations are not yet linked … but this you know of course. 

3 things that I noticed (see image with numbering for context)
1. I assume the title of the navigation you'll move to the shared file `website-legal-json`, I changed the EN title and added the DE as comment
2. This title is not needed
3. One icon in the list is smaller (let's see how it reacts with the actual translations, they should of course all be the same size)

I think we are almost there!

Screenshot 2024-02-05 at 17 47 22

**Comment by ssandino** [comment]
@DarkMenacer 1. Good, 2. Good, 3. Good – thanks for these last changes and for switching from draft to normal PR for review? The PR will also be used to finish #712.

**Comment by DarkMenacer** [comment]
Done
Screenshot 2024-02-07 at 00 40 50

**Comment by ssandino** [comment]
> 3. Once the actual title comes in, the icon regularises in size, so shouldn't be an issue hopefully but still I'll check the responsiveness again

I still had the issue with the slightly smaller icon:
Screenshot 2024-02-06 at 22 36 46

Found a easy work around with shorten the translation (so all good):
Screenshot 2024-02-06 at 22 36 37

**Review by ssandino — APPROVED** [review]
Looks good to me. Once this PR is merged, we can proceed to delete the outdated legal pages (those not organized under the 'legal' path) and set up some redirects to avoid 404 errors.

**Comment by mkue** [comment]
Very nice! Looks good to me :)

**Review by mkue — APPROVED** [review]

**Pull request merged**
