### PR TITLE
feature (website): sections for new landing page-2

### PR DESCRIPTION
**Pull request by DarkMenacer**

### CODE REVIEW

**Comment by DarkMenacer** [comment]
@mkue @ssandino 
I'm done with the next section: Monthly Income (albeit it is cosmetic for now)
For some reason, even the previous commits are being displayed here but thankfully only the files that I changed for the latest commits are displayed for the 'Files changed' section.

Also Mike, I had some doubts regarding taking the input and the overall working of the input component.

**Comment by ssandino** [comment]
@mkue not sure if you are up to date, but @DarkMenacer will present the landing page at the upcoming Townhall ❤️

**Comment by DarkMenacer** [comment]
@mkue, @ssandino 
Done with yet another section, Mobile Illustrations

**Comment by DarkMenacer** [comment]
@mkue, @ssandino 
Also wrapped up explainer-video
Also at this point, I realise some font size inconsistencies
Do not worry, once I am done with all sections, I’ll have some sort of a overall bird eye view at the entire page and make the consistency changes
For now my main focus is to get the pages up and running

**Comment by DarkMenacer** [comment]
@mkue @ssandino 
Let me know once you have gone through the code
Heavy changes coming in...I'll keep them on hold until you review these ones
I'll push the next batch after this one

**Comment by ssandino** [comment]
Thanks @DarkMenacer – I went through it visually and must say, we are definitely on the right track here. Nice to see it coming along.

> I had some doubts regarding taking the input and the overall working of the input component.

In my opinion, the monthly income input field can be a simple placeholder for now and addressed later, aligned with the donation process. Don't loose time there. 

A big (design) step forward will be when the blue sections extend across the full width of the page. Looking forward to this – but this might be your "heavy changes coming in"!

**Comment by DarkMenacer** [comment]
> A big (design) step forward will be when the blue sections extend across the full width of the page.

I'll need @mkue 's help here. It seems that, that shade of blue hasn't been added as the property type for `BaseContainer` component.
I tried adding `primary` to the list, but it doesn't seem to change anything
So I just proceeded without the background for now

**Comment by DarkMenacer** [comment]
@mkue @ssandino 
Done with quotes sections as well (Also had to rearrange testimonials section as I was confused between the two earlier)
Now only 5 things remain

- [ ] Navbar
- [ ] Hero Video
- [ ] SDG Goals
- [ ] Journal
- [ ] Footer

I'll hopefully wrap up Journal and SDG Goals by tonight

**Comment by DarkMenacer** [comment]
@mkue Extended background color to blue for relevant sections despite it displaying an error. Let's look into this whenever you have time

**Review by mkue — APPROVED** [review]

**Pull request merged**
