### PR TITLE
transparent bg on nav when hero video

### PR DESCRIPTION
**Pull request by mdumond**

### CODE REVIEW

**Comment by mdumond** [comment]
yes we did not test at all :upside_down_face: I will check that this week end

**Comment by mdumond** [comment]
I have just pushed a fix that fixes the nav background on scroll

**Comment by ssandino** [comment]
works 🙌🏼

**Review by ssandino — APPROVED** [review]

**Comment by mkue** [comment]
Very very cool🙌🏼 I'm super happy this is resolved now. It bothered me quite a bit that I didn't find a better solution initially🙃

I pushed one last commit that sets the default color to `null` in the `useNavbarBackgroundColor()` hook. This a) resolves an issue that the navbar stayed blue when navigating back to the home page, and b) makes it a bit more clear that this hook is there to overwrite the default background color (which is blue due to `theme-blue` that is used on the NavbarClient component).

**Review by mkue — APPROVED** [review]

**Pull request merged**
