### PR TITLE
[Shared] Update Readme with profiles of code contributors #55

### PR DESCRIPTION
**Pull request by Yatharth-Jain**
#55

Added Contributors Pictures in the contribution portion of the readme as shown in the picture
image

Kindly give a visit too for reconfirming 
Also can you provide me with the content to type in the Same portion of the readme

### CODE REVIEW

**Comment by ssandino** [comment]
@Yatharth-Jain thanks. We were aware of [contrib.rocks](https://github.com/lacolaco/contributors-img/), however, it didn't match our criteria. We would like to have something that is: 

- dynamic (it updates regularly by itself)
- and uses the SVG instead PNG format (sharper)

I think [this tool](https://github.com/dummy-crew/svg-contributors) could do the job. The last question would then be where to save it (whenever there is a change). A quick solution could be to save the generated SVG in a publicy accessible folder on a Google Drive (overwrite last file, so the referenced file in readme is always the newest).

**Review by ssandino — CHANGES_REQUESTED** [review]
@Yatharth-Jain thanks. We were aware of [contrib.rocks](https://github.com/lacolaco/contributors-img/), however, it didn't match our criteria. We would like to have something that is:

dynamic (it updates regularly by itself)

- and uses the SVG instead PNG format (sharper)
- I think [this tool](https://github.com/dummy-crew/svg-contributors) could do the job. 

The last question would then be where to save it (whenever there is a change). A quick solution could be to save the generated SVG in a publicy accessible folder on a Google Drive (overwrite last file, so the referenced file in readme is always the newest).

**Comment by Yatharth-Jain** [comment]
@ssandino thankyou for responding
i would like to ask few queries

**Comment by Yatharth-Jain** [comment]
@ssandino thank you for responding
I will try my best to achieve that .
there somethings i want to ask

first of all i guess the images from the [contrib.rocks](https://github.com/lacolaco/contributors-img/) which we fetch with the help of Img tag in readme should be updated if it create the image on request.

secondly if i have to make new image on every changes to the list of contributors then for that i have to make a scraper which will check for any change, thats my solution would you like to suggest some

thirdly the Repo you have given ,gave glitched svg when i used it as shown below

contributors

any solution for that

**Comment by ssandino** [comment]
Hi @Yatharth-Jain, thanks for the updated PR and good idea with updating it with a regular GitHub action (as you do know via another public repo). Looks good to me. 

@mkue @andrashee good for you? I would propose to deploy this PR and then see further if we can integrate the external GitHub action (see [here](https://github.com/Yatharth-Jain/Social-Income-contributors-list/blob/master/.github/workflows/actions.yml)) into our own workflow (to have not a dependency to another repo, but no risk so far as it's just importing one image that could fail)?

**Comment by andrashee** [comment]
Awesome! Will have a look at it tomorrow morning 😊

**Comment by andrashee** [comment]
> @Yatharth-Jain thanks. We were aware of [contrib.rocks](https://github.com/lacolaco/contributors-img/), however, it didn't match our criteria. We would like to have something that is:
> 
> * dynamic (it updates regularly by itself)

This is the case with @Yatharth-Jain's first suggestion. When you use `https://contrib.rocks/image?repo=socialincome-san/public` as img src it should get updated.

> * and uses the SVG instead PNG format (sharper)

True, it's not super crispy.

**Comment by andrashee** [comment]
> @mkue @andrashee good for you? I would propose to deploy this PR and then see further if we can integrate the external GitHub action (see [here](https://github.com/Yatharth-Jain/Social-Income-contributors-list/blob/master/.github/workflows/actions.yml)) into our own workflow (to have not a dependency to another repo, but no risk so far as it's just importing one image that could fail)?

Is the generated SVG better than the one generated by contrib.rocks?
Here a screenshot how it looks for me
Screenshot 2022-10-14 at 08 28 07

I personally would keep things simple here and use @Yatharth-Jain's first suggestion and just link to contrib.rocks. Having a Github action for this almost sounds a bit like an overkill to me.
E.g. we could add it as markdown to keep things consistent:
```
[![Contributors](https://contrib.rocks/image?repo=socialincome-san/public)](https://github.com/socialincome-san/public/graphs/contributors)

```

If we want to have generate it by ourselves, I would integrate the action into this repository instead of linking to an external one.

**Comment by Yatharth-Jain** [comment]
@ssandino @andrashee My PR is not complete yet as some errors are occuring in the GitHub Actions

And i am currently working on it and may require some time
In the mean time if you can check for the errors which are coming while environment setup of Github action in my Repo, That would be appreciated

**Comment by ssandino** [comment]
I wasn't aware of that contrib.rocks updates automatically. In my opinion, the large avatars generated by contrib.rocks are bit too obtrusive. However, it seems that there is a parameter `columns={number}` [now supported](https://github.com/lacolaco/contributors-img/issues/1110) which may lets us control the size of the avatars (by overwriting the default column count (12) with a higher number). So if this works, let's go with this solution for now – as it takes only a few minutes to get it up and running. 

@Yatharth-Jain feel free to make a second PR which only adds the code (with the addition to make the avatars smaller), so the commit is attributed to you as part of the Hacktoberfest : 
```
[![Contributors](https://contrib.rocks/image?repo=socialincome-san/public)](https://github.com/socialincome-san/public/graphs/contributors)

```

**Why I would then continue to aim and work on an SVG solution:** 
- SVG keeps the information in code which we can better access
- Lets us reuse parts on our website in ways we couldn't with a PNG
- i.e. even introduce optional line breaks in the single SVG holding all avatars 
- i.e. reuse each single avatars on our website by extracting the element (like each avatar floating over the page)

These example applications are out of scope of this issue, but the basic SVG would allow for tackle this in the future.

**Comment by Yatharth-Jain** [comment]
Ok @ssandino I will close this PR and will send a new one right away
Along with that i will look into this problem of svg just for my betterment and once that's finish i will let you know then that your decision to include it or not

**Comment by ssandino** [comment]
@Yatharth-Jain it's deployed. Thanks for looking into the SVG solution.

**Pull request closed without merging**
