### PR TITLE
Proofread and make corrections to README

### PR DESCRIPTION
**Pull request by jeslyw**
Minor grammar and sentence corrections to improve document readability

### CODE REVIEW

**Review by ssandino — APPROVED** [review]
Great job @jeslyw

**Comment by ssandino** [comment]
@jeslyw as you have done such a good job, let me ask you: would have time to go through the [UI Readme](https://github.com/socialincome-san/public/tree/main/ui) and the [Contribution.md ](https://github.com/socialincome-san/public/blob/main/ui/CONTRIBUTION.md)? I can of course open an issue if you like! Thanks again.

**Comment by jeslyw** [comment]
> @jeslyw as you have done such a good job, let me ask you: would have time to go through the [UI Readme](https://github.com/socialincome-san/public/tree/main/ui) and the [Contribution.md ](https://github.com/socialincome-san/public/blob/main/ui/CONTRIBUTION.md)? I can of course open an issue if you like! Thanks again.

@ssandino sure! :) I think it's an great project and would love to support in any way - just open an issue and assign it to me.

**Comment by ssandino** [comment]
Great! Just have to write whatever comment, so it lets me assign it to you.

**Pull request merged**
