### PR TITLE
[shared] Minor setup changes & marking checks required

### PR DESCRIPTION
**Pull request by andrashee**
- Starting from a plain repository, I still got some errors because the dependencies haven't been installed for the shared packages. Switched now to install everything. For me, `npm install` is quicker than `npm ci` since the later deletes the node_moduels every time.

Screenshot 2022-10-14 at 07 40 03

- to make the checks required, we need to set unique names for the jobs, otherwise I can't select them in the UI

### CODE REVIEW

**Comment by renestalder** [comment]
It's okay to use `npm install` locally (at least since version 7 or 8 I guess). It's just important that it is `npm clean-install` (`npm ci`) in the GitHub actions.

> For me, npm install is quicker than npm ci since the later deletes the node_moduels every time.

That's right. Just not as it can unexpected alter the package-lock file. But that's okay in our case locally.

**Comment by andrashee** [comment]
> It's okay to use `npm install` locally (at least since version 7 or 8 I guess). It's just important that it is `npm clean-install` (`npm ci`) in the GitHub actions.
> 

Let me change that in the actions.

> > For me, npm install is quicker than npm ci since the later deletes the node_moduels every time.
> 
> That's right. Just not as it can unexpected alter the package-lock file. But that's okay in our case locally.

**Review by renestalder — APPROVED** [review]
lgtm. That's great that we now have the full install everywhere because stuff is anyway so much interconnected now that it is easier and saver to just install everything.

**Comment by andrashee** [comment]
Configured that the checks are required

image

**Pull request merged**
