### PR TITLE
Adding path to smaller font package

### PR DESCRIPTION
**Pull request by ssandino**
For the Admin Tool and the UI

### CODE REVIEW

**Review by renestalder — APPROVED** [review]
@ssandino Should we maybe document somewhere what subset the `Sub` cut has?

**Comment by ssandino** [comment]
@renestalder that could be helpful. Lineto actually provided us a html-file, which displays the entire character set of the cut.

Not sure how this would run directly in our setup (when copied to the shared folder). Locally it runs fine:
Screenshot 2022-12-12 at 16 36 23

Should I add the html-files in a separate PR to the font folder?

**Comment by renestalder** [comment]
@ssandino I'm confused. If this is the Basic Latin range one, what does the standard `Web` font cover?

**Comment by ssandino** [comment]
The standard web version covers a lot more special characters (which we never use), in example: 

Screenshot 2022-12-12 at 17 04 28

**Review by socialincome-dev — APPROVED** [review]

**Comment by ssandino** [comment]
@mkue I think there is a approval from you as code owner necessary ... otherwise it's blocked

**Review by andrashee — APPROVED** [review]
🎉

**Pull request merged**
